services:
  frontend:
    image: frontend:blue
    container_name: frontend_blue
    ports:
      - "5174:5173"
    # volumes:
    #   - ./frontend:/frontend
    #   - /frontend/node_modules
    networks:
      - app_network
    restart: always
    environment:
      - TZ=Asia/Seoul

  backend:
    image: backend:blue
    container_name: backend_blue
    ports:
      - "8081:8080"
    environment:
      TZ: Asia/Seoul
      JAVA_SECURITY_PROPERTIES: |
        jdk.internal.reflect.permitAll=true
        jdk.reflect.allowNativeAccess=true
    env_file:
      - .env
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - app_network
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  ai:
    image: ai:blue
    container_name: ai_blue
    ports:
      - "8001:8000"
    # volumes:
    #   - ./ai:/ai
    environment:
      - PYTHONPATH=/ai
      - TZ=Asia/Seoul
    networks:
      - app_network
    restart: always

networks:
  app_network:
    external: true
