services:
  frontend:
    build: ./frontend
    container_name: frontend_green
    ports:
      - "5175:5173"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    networks:
      - app_network
    restart: always
    environment:
      - TZ=Asia/Seoul

  backend:
    build: ./backend
    container_name: backend_green
    ports:
      - "8082:8080"
    depends_on:
      mysql:
        condition: service_started
    environment:
      TZ: Asia/Seoul
      JAVA_SECURITY_PROPERTIES: |
        jdk.internal.reflect.permitAll=true
        jdk.reflect.allowNativeAccess=true
    env_file:
      - .env
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - app_network
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  ai:
    build: ./ai
    container_name: ai_green
    ports:
      - "8002:8000"
    volumes:
      - ./ai:/ai
    environment:
      - PYTHONPATH=/ai
      - TZ=Asia/Seoul
    networks:
      - app_network
    restart: always

networks:
  app_network:
    external: true
