spring:
  application:
    name: backend
    version: v1
  config:
    import: optional:file:.env[.properties]

  # MySQL
  datasource:
    driver-class-name: ${MYSQL_DRIVER}
    url: jdbc:mysql://${MYSQL_URL}/${MYSQL_SCHEMA}?serverTimezone=Asia/Seoul
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

server:
  port: 8080